from enum import StrEnum


class EventType(StrEnum):
    APPLICATION_SUBMITTED = "APPLICATION_SUBMITTED"
    KYC_RESULT = "KYC_RESULT"
    DEVICE_OBSERVED = "DEVICE_OBSERVED"
    CAMERA_METADATA_OBSERVED = "CAMERA_METADATA_OBSERVED"
    LOGIN_ATTEMPT = "LOGIN_ATTEMPT"
    BEHAVIORAL_SIGNAL_OBSERVED = "BEHAVIORAL_SIGNAL_OBSERVED"
    TRANSACTION_AUTHORIZED = "TRANSACTION_AUTHORIZED"
    PAYMENT_ATTEMPTED = "PAYMENT_ATTEMPTED"
    PAYMENT_SETTLED = "PAYMENT_SETTLED"
    CHARGEBACK_RECEIVED = "CHARGEBACK_RECEIVED"
    CONSORTIUM_HIT = "CONSORTIUM_HIT"
    DECISION_CREATED = "DECISION_CREATED"
    MANUAL_REVIEW_DECIDED = "MANUAL_REVIEW_DECIDED"
    LABEL_CREATED = "LABEL_CREATED"


class EntityType(StrEnum):
    USER = "USER"
    PERSON = "PERSON"
    BUSINESS = "BUSINESS"
    DEVICE = "DEVICE"
    IP_ADDRESS = "IP_ADDRESS"
    EMAIL = "EMAIL"
    PHONE = "PHONE"
    ADDRESS = "ADDRESS"
    CARD = "CARD"
    BANK_ACCOUNT = "BANK_ACCOUNT"
    DOCUMENT = "DOCUMENT"
    SESSION = "SESSION"
    TRANSACTION = "TRANSACTION"
    APPLICATION = "APPLICATION"


class FraudTypology(StrEnum):
    SYNTHETIC_IDENTITY = "SYNTHETIC_IDENTITY"
    ACCOUNT_TAKEOVER = "ACCOUNT_TAKEOVER"
    CARD_TESTING = "CARD_TESTING"
    FIRST_PARTY_FRAUD = "FIRST_PARTY_FRAUD"
    MONEY_MULE = "MONEY_MULE"
    APP_SCAM = "APP_SCAM"
    BEC = "BEC"
    DEEPFAKE_LIVENESS = "DEEPFAKE_LIVENESS"
    BUST_OUT = "BUST_OUT"
    UNKNOWN = "UNKNOWN"


class RiskTier(StrEnum):
    GREEN = "GREEN"
    YELLOW = "YELLOW"
    RED = "RED"


class DecisionAction(StrEnum):
    APPROVE = "APPROVE"
    STEP_UP_AUTH = "STEP_UP_AUTH"
    MANUAL_REVIEW = "MANUAL_REVIEW"
    BLOCK = "BLOCK"
    HOLD_FUNDS = "HOLD_FUNDS"
    BREAK_THE_SPELL = "BREAK_THE_SPELL"
    SAR_DRAFT = "SAR_DRAFT"
    NO_ACTION = "NO_ACTION"


class ReviewOutcome(StrEnum):
    CONFIRMED_FRAUD = "CONFIRMED_FRAUD"
    CONFIRMED_LEGITIMATE = "CONFIRMED_LEGITIMATE"
    NEEDS_MORE_INFO = "NEEDS_MORE_INFO"
    ESCALATED = "ESCALATED"
    DUPLICATE = "DUPLICATE"
    UNREVIEWABLE = "UNREVIEWABLE"


class FeatureFreshnessStatus(StrEnum):
    FRESH = "FRESH"
    STALE = "STALE"
    MISSING = "MISSING"
    DEGRADED = "DEGRADED"


class PaymentRail(StrEnum):
    ACH = "ACH"
    RTP = "RTP"
    DEBIT_CARD = "DEBIT_CARD"
    PUSH_TO_CARD = "PUSH_TO_CARD"


class LabelValue(StrEnum):
    FRAUD = "FRAUD"
    LEGITIMATE = "LEGITIMATE"
    UNKNOWN = "UNKNOWN"
